=== miguel-armas-unmsm/course-java7/src/main/resources/xml/universityCard.xsd
<?identification version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="universityCard">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="year" type="xs:integer"/>
        <xs:element name="expirationDate" type="xs:string"/>
        <xs:element name="student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="firstName" type="xs:string"/>
              <xs:element name="lastName" type="xs:string"/>
              <xs:element name="dni" type="xs:string"/>
              <xs:element name="code" type="xs:string"/>
              <xs:element name="incomeYear" type="xs:string"/>
              <xs:element name="career">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="careerName" type="xs:string"/>
                    <xs:element name="faculty">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="facultyName" type="xs:string"/>
                          <xs:element name="university">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="universityName" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== miguel-armas-unmsm/course-java7/src/main/resources/xml/universityCard.xml
<?identification version="1.0" encoding="UTF-8"?>
<universityCard xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="universityCard.xsd">
        <year>2021</year>
        <expirationDate>2022-12-13</expirationDate>
        <student>
                <firstName>KENT JHUNIOR</firstName>
                <lastName>CUADROS RAMOS</lastName>
                <dni>76517361</dni>
                <code>15200134</code>
                <incomeYear>2021-2</incomeYear>
                <career>
                        <careerName>INGENIERIA DE SOFTWARE</careerName>
                        <faculty>
                                <facultyName>INGENIERÍA DE SISTEMAS E INFORMÁTICA</facultyName>
                                <university>
                                        <universityName>UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS</universityName>
                                </university>
                        </faculty>
                </career>
        </student>
</universityCard>
